version: '3.7'
services:
  oms-application:
   image: wortiz1027/oms-application:latest
   container_name: oms-application
   hostname: oms-application
   restart: always
   ports:
    - 8300:80
   environment:
    - HOST_API_GATEWAY=http://10.39.1.85:9092
   networks:
    - ntw_backend
networks:
  ntw_backend:
    external: true